import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    features: 'Features',
    login: 'Login',
    signUp: 'Sign Up',
    createFreeVault: 'Create Free Vault',

    // Hero section
    heroTitle: 'Focus on learning, we\'ll handle the sync.',
    heroDescription: 'StudySync is your private vault for academic notes. Organize your thoughts, track your progress, and keep everything in one secure place.',
    howItWorks: 'How it Works',
    synced: 'Synced',

    // Features section
    powerfulCapabilities: 'Powerful Capabilities',
    capabilitiesSubtitle: 'We stripped away the social noise to give you a dedicated workspace for deep learning.',
    
    instantSync: 'Instant Sync',
    instantSyncDescription: 'Your notes move at the speed of thought. Edit on desktop, read on mobile instantly.',
    
    deepSearch: 'Deep Search',
    deepSearchDescription: 'Find any keyword across years of semesters in milliseconds.',
    
    focusMode: 'Focus Mode',
    focusModeDescription: 'A distraction-free markdown interface designed for long study sessions.',
    
    privateVault: 'Private Vault',
    privateVaultDescription: 'Your academic data is encrypted and private. We don\'t sell your notes to anyone.',
    
    aiSummaries: 'AI Summaries',
    aiSummariesDescription: 'Automatically generate concise summaries of your lengthy notes.',
    
    pdfImport: 'PDF Import',
    pdfImportDescription: 'Import and annotate PDF documents directly in your vault.',
    
    smartTags: 'Smart Tags',
    smartTagsDescription: 'AI-powered tagging system that organizes your notes automatically.',
    
    flashcards: 'Flashcards',
    flashcardsDescription: 'Create and study flashcards from your notes with spaced repetition.',
    
    // Sidebar items
    library: 'Library',
    study: 'Study',
    account: 'Account',
    schedule: 'Schedule',
    tags: 'Tags',
    studyAI: 'Study AI',
    settings: 'Settings',

    // Workflow section
    simpleEfficient: 'Simple & Efficient',
    workflowSubtitle: 'We designed StudySync to get out of your way so you can focus on what matters most: your education.',
    
    capture: 'Capture',
    captureTitle: '01. Capture',
    captureDescription: 'Write down your lecture notes in our lightning-fast markdown editor. No distractions, just you and your thoughts.',
    
    organize: 'Organize',
    organizeTitle: '02. Organize',
    organizeDescription: 'Categorize your notes into subjects and topics. Our smart tagging system makes sure you never lose a page again.',
    
    sync: 'Sync',
    syncTitle: '03. Sync',
    syncDescription: 'Your data is automatically synced across all your devices. Start on your laptop, finish on your phone—instantly.',

    // CTA section
    ctaTitle: 'Ready to Transform Your Study Experience?',
    ctaDescription: 'Join thousands of students who have already discovered the power of organized, secure, and intelligent note-taking.',
    startFree: 'Start Free',
    noCreditCard: 'No credit card required · Free forever · Cancel anytime',

    // Footer
    footerDescription: 'Your personal study vault. Secure, private, and designed for deep learning.',
    product: 'Product',
    pricing: 'Pricing',
    changelog: 'Changelog',
    company: 'Company',
    aboutUs: 'About Us',
    blog: 'Blog',
    careers: 'Careers',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    copyright: '© 2026 StudySync. All rights reserved.',

    // App shell
    backToLanding: 'Back to Landing',
    dashboard: 'Dashboard',
    notes: 'Notes',
    progress: 'Progress',
    collab: 'Collab',
    gpa: 'GPA',

    // Authentication
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    enterEmail: 'Please enter your email',
    enterPassword: 'Please enter your password',
    rememberMe: 'Remember me',
    processing: 'Processing...',
    loginFailed: 'Login failed',
    registerFailed: 'Registration failed',
    passwordMismatch: 'Passwords do not match',
    passwordMatch: 'Passwords match',
    passwordTooShort: 'Password must be at least 6 characters',
    passwordStrength: 'Password Strength',
    weakPassword: 'Weak',
    mediumPassword: 'Medium',
    strongPassword: 'Strong',
    allRightsReserved: 'All rights reserved.',

    // Theme selector
    selectTheme: 'Select Theme',
    selectLanguage: 'Select Language',
    defaultTheme: 'Default Theme',
    lightTheme: 'Light Theme',
    darkTheme: 'Dark Theme',

    // Progress View
    progressTracking: 'Progress Tracking',
    progressDescription: 'Monitor your study habits and thesis milestones',
    logProgress: 'Log Progress',
    addMilestone: 'Add Milestone',
    hoursThisWeek: 'Hours This Week',
    ofPlanned: 'of {hours}h planned',
    planAdherence: 'Plan Adherence',
    vsPlannedHours: 'vs planned hours',
    thesisProgress: 'Thesis Progress',
    milestonesDone: 'Milestones Done',
    completed: 'completed',
    studyActivityHeatmap: 'Study Activity Heatmap (Last 28 Days)',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
    less: 'Less',
    more: 'More',
    progressLogs: 'Progress Logs',
    thesisMilestones: 'Thesis Milestones',
    noProgressLogs: 'No progress logs yet. Start tracking your daily study hours!',
    noThesisMilestones: 'No thesis milestones yet. Add your first chapter milestone!',
    date: 'Date',
    hoursStudied: 'Hours Studied',
    hoursPlanned: 'Hours Planned',
    ofPlannedShort: 'of {hours}h planned',
    hStudied: 'h studied',
    mood: 'Mood',
    exhausted: 'Exhausted',
    tired: 'Tired',
    okay: 'Okay',
    good: 'Good',
    energized: 'Energized',
    notesOptional: 'Notes (optional)',
    whatDidYouStudyToday: 'What did you study today?',
    cancel: 'Cancel',
    saveLog: 'Save Log',
    saving: 'Saving...',
    logDailyProgress: 'Log Daily Progress',
    addThesisMilestone: 'Add Thesis Milestone',
    title: 'Title',
    targetDate: 'Target Date',
    pagesTarget: 'Pages Target',
    pagesDone: 'Pages Done',
    taskStatus: 'Status',
    pending: 'Pending',
    inProgress: 'In Progress',
    complete: 'Complete',
    milestoneAdded: 'Milestone added!',
    progressLogged: 'Progress logged!',
    logDeleted: 'Log deleted',
    milestoneDeleted: 'Milestone deleted',
    dateRequired: 'Date is required',
    titleAndTargetDateRequired: 'Title and target date required',
    failedToSaveLog: 'Failed to save log',
    failedToAddMilestone: 'Failed to add milestone',
    failedToDeleteLog: 'Failed to delete log',
    failedToDeleteMilestone: 'Failed to delete milestone',
    failedToLoadProgressData: 'Failed to load progress data',
    failedToUpdateMilestone: 'Failed to update milestone',
    egChapterIntroduction: 'e.g. Chapter 1 - Introduction',

    // Collab View
    collabTitle: 'Collaboration Hub',
    collabDescription: 'Shared task boards for group projects with @mention notifications',
    newTask: 'New Task',
    noTasksHere: 'No tasks here',
    projectName: 'Project Name',
    projectNameRequired: 'Project name and title are required',
    taskTitle: 'Task Title',
    assignedTo: 'Assigned To',
    assignedBy: 'Assigned By',
    priority: 'Priority',
    dueDate: 'Due Date',
    mentions: '@Mentions (comma separated)',
    description: 'Description',
    createTask: 'Create Task',
    creating: 'Creating...',
    taskCreated: 'Task created!',
    failedToCreateTask: 'Failed to create task',
    failedToUpdateTask: 'Failed to update task',
    failedToDeleteTask: 'Failed to delete task',
    taskDeleted: 'Task deleted',
    failedToLoadTasks: 'Failed to load tasks',
    recentActivity: 'Recent Activity',
    allProjects: 'All Projects',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
    toDo: 'To Do',
    done: 'Done',

    // GPA View
    gpaPredictor: 'GPA Predictor',
    gpaPredictorDescription: 'Forecast your semester GPA based on study inputs',
    addCourse: 'Add Course',
    currentGpa: 'Current GPA',
    predictedGpa: 'Predicted GPA',
    targetGpa: 'Target GPA',
    totalCredits: 'Total Credits',
    basedOnCurrentGrades: 'Based on current grades',
    withStudyHoursFactoredIn: 'With study hours factored in',
    yourGoalThisSemester: 'Your goal this semester',
    coursesEnrolled: '{{count}} courses enrolled',
    gpaForecastVisualization: 'GPA Forecast Visualization',
    aiInsight: 'AI Insight',
    gpaBoostInsight: 'Your study hours are projected to boost your GPA by +{{points}} points. Keep it up!',
    gpaImprovementInsight: 'Increasing your weekly study hours could improve your predicted GPA. Aim for {{hours}}h/week per course.',
    enrolledCourses: 'Enrolled Courses ({{count}})',
    noCoursesAdded: 'No courses added yet. Add your courses to predict your GPA!',
    studyHrsWk: 'Study Hrs/Wk',
    gpaPoints: 'GPA Points',
    semester: 'Semester',
    currentGrade: 'Current Grade',
    targetGrade: 'Target Grade',
    studyHoursPerWeek: 'Study Hours / Week',
    'e.g.CalculusIII': 'e.g. Calculus III',
    adding: 'Adding...',
    courseNameRequired: 'Course name is required',
    courseAdded: 'Course added!',
    failedToAddCourse: 'Failed to add course',
    updated: 'Updated!',
    failedToUpdate: 'Failed to update',
    courseRemoved: 'Course removed',
    failedToDelete: 'Failed to delete',
    failedToLoadGpaData: 'Failed to load GPA data',

    // Integrations
    integrations: 'Integrations',
    integrationsDescription: 'Connect productivity tools, calendars, and AI services',
    connected: 'Connected',
    connecting: 'Connecting...',
    connect: 'Connect',
    disconnect: 'Disconnect',
    refresh: 'Refresh',
    integrationConnected: '{{name}} connected!',
    integrationDisconnected: 'Integration disconnected',
    integrationRefreshed: 'Integration refreshed',
    failedToRefreshIntegration: 'Failed to refresh integration',
    failedToDisconnectIntegration: 'Failed to disconnect integration',
    apiKeyRequired: 'API Key required',
    enterApiKey: 'Enter your API key',
    apiKeySecurityNote: 'Your API key is encrypted and stored securely.',
    connectedIntegrations: 'Connected Integrations',
    availableIntegrations: 'Available Integrations',
    wantMoreIntegrations: 'Want More Integrations?',
    integrationRequestDescription: 'Request a new integration and we\'ll add it.',
    requestIntegration: 'Request Integration',

    // Schedule View
    failedToLoadSchedule: 'Failed to load schedule',
    sessionAdded: 'Session added!',
    failedToCreateSession: 'Failed to create session',
    failedToUpdateSession: 'Failed to update session',
    failedToDeleteSession: 'Failed to delete session',
    sessionDeleted: 'Session deleted',
    titleAndDateRequired: 'Title and date are required',
    aiRecommendationLoaded: 'AI recommendation loaded',
    reviewAndSaveSession: 'Review and save the session',

    // Team Tasks
    teamTasks: 'Team Tasks',
    teamTasksDescription: 'Manage shared tasks for your study group',
    addTask: 'Add Task',
    totalTasks: 'Total Tasks',
    allTasks: 'All Tasks',
    noTasksYet: 'No tasks yet',
    failedToLoadTeamTasks: 'Failed to load team tasks',
    titleAndDueDateRequired: 'Title and due date are required',
    unassigned: 'Unassigned',
    review: 'Review',
    taskTitlePlaceholder: 'Task title...',
    taskDescriptionPlaceholder: 'Optional description...',
    addTeamTask: 'Add Team Task',
  },
  zh: {
    // 导航
    features: '功能',
    login: '登录',
    signUp: '注册',
    createFreeVault: '创建免费保险库',

    // 英雄区
    heroTitle: '专注学习，我们来处理同步。',
    heroDescription: 'StudySync 是您的私人学术笔记保险库。组织您的思路，跟踪您的进度，并将所有内容保存在一个安全的地方。',
    howItWorks: '工作原理',
    synced: '已同步',

    // 功能区
    powerfulCapabilities: '强大功能',
    capabilitiesSubtitle: '我们剥离了社交噪音，为您提供一个专注深度学习的工作空间。',
    
    instantSync: '即时同步',
    instantSyncDescription: '您的笔记以思维的速度移动。在桌面端编辑，在移动端即时阅读。',
    
    deepSearch: '深度搜索',
    deepSearchDescription: '在毫秒内搜索数年学期的任何关键词。',
    
    focusMode: '专注模式',
    focusModeDescription: '专为长时间学习会话设计的无干扰 Markdown 界面。',
    
    privateVault: '私人保险库',
    privateVaultDescription: '您的学术数据经过加密且私密。我们不会将您的笔记出售给任何人。',
    
    aiSummaries: 'AI 摘要',
    aiSummariesDescription: '自动生成冗长笔记的简洁摘要。',
    
    pdfImport: 'PDF 导入',
    pdfImportDescription: '直接在您的保险库中导入和注释 PDF 文档。',
    
    smartTags: '智能标签',
    smartTagsDescription: 'AI 驱动的标签系统，自动组织您的笔记。',
    
    flashcards: '闪卡',
    flashcardsDescription: '从您的笔记创建和学习闪卡，采用间隔重复法。',
    
    // 侧边栏项目
    library: '资料库',
    study: '学习',
    account: '账户',
    schedule: '日程',
    tags: '标签',
    studyAI: '学习 AI',
    settings: '设置',

    // 工作流程区
    simpleEfficient: '简单高效',
    workflowSubtitle: '我们设计 StudySync 让它不挡您的道，这样您就可以专注于最重要的事情：您的教育。',
    
    capture: '捕获',
    captureTitle: '01. 捕获',
    captureDescription: '在我们闪电般的 Markdown 编辑器中记下您的讲座笔记。没有干扰，只有您和您的想法。',
    
    organize: '组织',
    organizeTitle: '02. 组织',
    organizeDescription: '将您的笔记分类到科目和主题。我们的智能标签系统确保您再也不会丢失任何页面。',
    
    sync: '同步',
    syncTitle: '03. 同步',
    syncDescription: '您的数据自动同步到所有设备。在笔记本电脑上开始，在手机上完成——即时同步。',

    // CTA 区
    ctaTitle: '准备好改变您的学习体验了吗？',
    ctaDescription: '加入数千名已经发现组织化、安全且智能笔记记录力量的学生。',
    startFree: '免费开始',
    noCreditCard: '无需信用卡 · 永久免费 · 随时取消',

    // 页脚
    footerDescription: '您的私人学习保险库。安全、私密，专为深度学习设计。',
    product: '产品',
    pricing: '定价',
    changelog: '更新日志',
    company: '公司',
    aboutUs: '关于我们',
    blog: '博客',
    careers: '招聘',
    legal: '法律',
    privacyPolicy: '隐私政策',
    termsOfService: '服务条款',
    copyright: '© 2026 StudySync. 保留所有权利。',

    // 应用外壳
    backToLanding: '返回首页',
    dashboard: '仪表板',
    notes: '笔记',
    progress: '进度',
    collab: '协作',
    gpa: 'GPA',

    // 认证
    email: '邮箱',
    password: '密码',
    confirmPassword: '确认密码',
    enterEmail: '请输入您的邮箱',
    enterPassword: '请输入密码',
    rememberMe: '记住我',
    processing: '处理中...',
    loginFailed: '登录失败',
    registerFailed: '注册失败',
    passwordMismatch: '密码不匹配',
    passwordMatch: '密码匹配',
    passwordTooShort: '密码长度至少为6位',
    passwordStrength: '密码强度',
    weakPassword: '弱',
    mediumPassword: '中',
    strongPassword: '强',
    allRightsReserved: '保留所有权利。',

    // 主题选择器
    selectTheme: '选择主题',
    selectLanguage: '选择语言',
    defaultTheme: '默认主题',
    lightTheme: '浅色主题',
    darkTheme: '深色主题',

    // 进度视图
    progressTracking: '进度跟踪',
    progressDescription: '监控您的学习习惯和论文里程碑',
    logProgress: '记录进度',
    addMilestone: '添加里程碑',
    hoursThisWeek: '本周学习时长',
    ofPlanned: '计划学习 {hours} 小时',
    planAdherence: '计划完成率',
    vsPlannedHours: '与计划学习时长对比',
    thesisProgress: '论文进度',
    milestonesDone: '已完成里程碑',
    completed: '已完成',
    studyActivityHeatmap: '学习活动热图（过去28天）',
    mon: '周一',
    tue: '周二',
    wed: '周三',
    thu: '周四',
    fri: '周五',
    sat: '周六',
    sun: '周日',
    less: '少',
    more: '多',
    progressLogs: '进度日志',
    thesisMilestones: '论文里程碑',
    noProgressLogs: '暂无进度日志。开始记录您的每日学习时长吧！',
    noThesisMilestones: '暂无论文里程碑。添加您的第一个章节里程碑吧！',
    date: '日期',
    hoursStudied: '学习时长',
    hoursPlanned: '计划时长',
    ofPlannedShort: '计划学习 {hours} 小时',
    hStudied: '小时学习',
    mood: '心情',
    exhausted: '筋疲力尽',
    tired: '疲惫',
    okay: '还行',
    good: '很好',
    energized: '精力充沛',
    notesOptional: '备注（可选）',
    whatDidYouStudyToday: '今天您学了什么？',
    cancel: '取消',
    saveLog: '保存日志',
    saving: '保存中...',
    logDailyProgress: '记录每日进度',
    addThesisMilestone: '添加论文里程碑',
    title: '标题',
    targetDate: '目标日期',
    pagesTarget: '目标页数',
    pagesDone: '已完成页数',
    taskStatus: '状态',
    pending: '待处理',
    inProgress: '进行中',
    complete: '已完成',
    milestoneAdded: '里程碑已添加！',
    progressLogged: '进度已记录！',
    logDeleted: '日志已删除',
    milestoneDeleted: '里程碑已删除',
    dateRequired: '日期为必填项',
    titleAndTargetDateRequired: '标题和目标日期为必填项',
    failedToSaveLog: '保存日志失败',
    failedToAddMilestone: '添加里程碑失败',
    failedToDeleteLog: '删除日志失败',
    failedToDeleteMilestone: '删除里程碑失败',
    failedToLoadProgressData: '加载进度数据失败',
    failedToUpdateMilestone: '更新里程碑失败',
    egChapterIntroduction: '例如：第1章 - 引言',

    // 协作视图
    collabTitle: '协作中心',
    collabDescription: '用于小组项目的共享任务板，带有 @ 提及通知',
    newTask: '新建任务',
    noTasksHere: '暂无任务',
    projectName: '项目名称',
    projectNameRequired: '项目名称和标题为必填项',
    taskTitle: '任务标题',
    assignedTo: '指派给',
    assignedBy: '创建者',
    priority: '优先级',
    dueDate: '截止日期',
    mentions: '@提及（逗号分隔）',
    description: '描述',
    createTask: '创建任务',
    creating: '创建中...',
    taskCreated: '任务已创建！',
    failedToCreateTask: '创建任务失败',
    failedToUpdateTask: '更新任务失败',
    failedToDeleteTask: '删除任务失败',
    taskDeleted: '任务已删除',
    failedToLoadTasks: '加载任务失败',
    recentActivity: '最近活动',
    allProjects: '所有项目',
    low: '低',
    medium: '中',
    high: '高',
    urgent: '紧急',
    toDo: '待办',
    done: '已完成',

    // GPA 视图
    gpaPredictor: 'GPA预测器',
    gpaPredictorDescription: '根据学习输入预测您的学期GPA',
    addCourse: '添加课程',
    currentGpa: '当前GPA',
    predictedGpa: '预测GPA',
    targetGpa: '目标GPA',
    totalCredits: '总学分',
    basedOnCurrentGrades: '基于当前成绩',
    withStudyHoursFactoredIn: '考虑学习时长',
    yourGoalThisSemester: '本学期目标',
    coursesEnrolled: '已注册课程 ({{count}})',
    gpaForecastVisualization: 'GPA预测可视化',
    aiInsight: 'AI洞察',
    gpaBoostInsight: '您的学习时长预计将提高GPA +{{points}}分。继续保持！',
    gpaImprovementInsight: '增加每周学习时长可以提高您的预测GPA。目标是每门课程{{hours}}小时/周。',
    enrolledCourses: '已注册课程 ({{count}})',
    noCoursesAdded: '尚未添加课程。添加课程以预测您的GPA！',
    studyHrsWk: '学习时长/周',
    gpaPoints: 'GPA分数',
    semester: '学期',
    currentGrade: '当前成绩',
    targetGrade: '目标成绩',
    studyHoursPerWeek: '每周学习时长',
    'e.g.CalculusIII': '例如：微积分III',
    adding: '添加中...',
    courseNameRequired: '课程名称是必需的',
    courseAdded: '课程添加成功！',
    failedToAddCourse: '添加课程失败',
    updated: '更新成功！',
    failedToUpdate: '更新失败',
    courseRemoved: '课程已移除',
    failedToDelete: '删除失败',
    failedToLoadGpaData: '加载GPA数据失败',

    // Integrations 视图
    integrations: '集成',
    connectYourLmsAndCalendarTools: '连接您的LMS和日历工具，实现无缝学术同步',
    integrationsActive: '{{count}} 个集成已激活',
    noIntegrationsConnected: '未连接任何集成',
    yourAcademicDataIsSyncing: '您的学术数据正在自动同步',
    connectLmsToolsToGetStarted: '连接Canvas、Blackboard或Google Calendar开始使用',
    connected: '已连接',
    syncing: '同步中...',
    notConnected: '未连接',
    lastSync: '最后同步',
    connect: '连接',
    syncNow: '立即同步',
    disconnect: '断开连接',
    howIntegrationsWork: '集成如何工作',
    connectLms: '连接LMS',
    connectLmsDescription: '使用您的API密钥或机构URL链接您的Canvas或Blackboard账户。',
    autoSync: '自动同步',
    autoSyncDescription: '截止日期、作业和考试日期会自动导入到您的日程中。',
    exportAndShare: '导出和共享',
    exportAndShareDescription: '将您的学习计划推送到Google Calendar并与您的学术顾问共享进度。',
    connectIntegration: '连接 {{name}}',
    demoIntegrationNote: '这是一个演示集成。在生产环境中，您将使用机构凭证进行身份验证。',
    googleAccountEmail: 'Google账户邮箱',
    apiKeyOrInstitutionUrl: 'API密钥或机构URL',
    yourGmailCom: 'your@gmail.com',
    canvasUrlOrApiKey: 'https://canvas.university.edu 或 API密钥',
    advisorEmail: '顾问邮箱',
    advisorEmailPlaceholder: 'advisor@university.edu',
    connecting: '连接中',
    pleaseEnterApiKeyOrUrl: '请输入您的API密钥或URL',
    integrationConnected: '{{name}} 已连接！',
    yourDataWillSyncAutomatically: '您的数据将自动同步。',
    connectTheIntegrationFirst: '请先连接集成',
    syncedDeadlines: '已从 {{name}} 同步 {{count}} 个截止日期！',
    studySessionsExported: '学习时段已导出到Google Calendar！',
    progressReportShared: '进度报告已与您的顾问共享！',
    syncFailedPleaseTryAgain: '同步失败，请重试。',
    integrationDisconnected: '集成已断开连接',
    integrationRefreshed: '集成已刷新',
    failedToRefreshIntegration: '刷新集成失败',
    failedToDisconnectIntegration: '断开集成连接失败',
    apiKeyRequired: '需要API密钥',
    enterApiKey: '输入您的API密钥',
    apiKeySecurityNote: '您的API密钥已加密并安全存储。',
    connectedIntegrations: '已连接的集成',
    availableIntegrations: '可用的集成',
    wantMoreIntegrations: '想要更多集成？',
    integrationRequestDescription: '请求新集成，我们会将其添加到路线图中。',
    requestIntegration: '请求集成',

    // Schedule View
    failedToLoadSchedule: '加载日程失败',
    sessionAdded: '学习时段已添加！',
    failedToCreateSession: '创建学习时段失败',
    failedToUpdateSession: '更新学习时段失败',
    failedToDeleteSession: '删除学习时段失败',
    sessionDeleted: '学习时段已删除',
    titleAndDateRequired: '标题和日期为必填项',
    aiRecommendationLoaded: 'AI推荐已加载',
    reviewAndSaveSession: '检查并保存该学习时段',

    // Team Tasks
    teamTasks: '团队任务',
    teamTasksDescription: '管理学习小组的共享任务',
    addTask: '添加任务',
    totalTasks: '总任务数',
    allTasks: '所有任务',
    noTasksYet: '暂无任务',
    failedToLoadTeamTasks: '加载团队任务失败',
    titleAndDueDateRequired: '标题和截止日期为必填项',
    unassigned: '未分配',
    review: '审核',
    taskTitlePlaceholder: '任务标题...',
    taskDescriptionPlaceholder: '可选描述...',
    addTeamTask: '添加团队任务',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<string>('zh');

  const t = (key: string, params?: Record<string, string | number>): string => {
    const translation = translations[language as keyof typeof translations]?.[key as keyof typeof translations.en] || key;
    if (!params) return translation;
    return Object.entries(params).reduce((acc, [key, value]) => acc.replace(new RegExp(`\{${key}\}`, 'g'), String(value)), translation);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};